# Generated by Django 5.1.6 on 2025-06-30 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_preparation_step_recipe_preparation_steps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='preparation_step_is_html',
            new_name='preparation_steps_is_html',
        ),
    ]
